FROM centos

MAINTAINER Lothar Wieske <lothar.wieske@gmail.com>

RUN yum update -y && \
    curl --insecure --junk-session-cookies --location --remote-name --silent --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8uUPDATE-bBUILD/jre-8uUPDATE-linux-x64.rpm && \
    yum localinstall -y jre-8uUPDATE-linux-x64.rpm && \
    rm jre-8uUPDATE-linux-x64.rpm

ENV JAVA_HOME=/usr/java/default \
    LANG=en_US.UTF-8 \
    LC_ALL=en_US.UTF-8
